use minhasvacinas;

INSERT INTO vacinas_existentes (nome_vac) VALUES
('COVID-19'),
('BCG'),
('Hepatite B'),
('DTP (Difteria, Tétano e Coqueluche)'),
('Sarampo, Caxumba e Rubéola (Tríplice Viral)'),
('Poliomielite'),
('Febre Amarela'),
('Hepatite A'),
('HPV (Papilomavírus Humano)'),
('Varicela (Catapora)'),
('Meningite Meningocócica'),
('Meningite Pneumocócica'),
('Hepatite C'),
('Dengue'),
('Zika'),
('Chikungunya'),
('Gripe (Influenza)'),
('Rotavírus'),
('Pneumonia'),
('Tétano'),
('Difteria'),
('Coqueluche'),
('Hepatite E'),
('Cólera'),
('Tuberculose'),
('Meningite Hib'),
('Tifo'),
('Febre Tifoide'),
('Hepatite D'),
('Hepatite F'),
('Hepatite G'),
('Malária'),
('Leishmaniose'),
('Raiva'),
('Ebola'),
('Zoster (Herpes Zoster)'),
('HPV (Papilomavírus Humano) Tipo 9'),
('Hepatite B Recombinante'),
('Hepatite A Recombinante'),
('Hepatite C Recombinante'),
('Hepatite E Recombinante'),
('Hepatite G Recombinante'),
('Malária Recombinante'),
('Leishmaniose Recombinante'),
('Raiva Recombinante'),
('Ebola Recombinante'),
('Zoster Recombinante'),
('HPV (Papilomavírus Humano) Tipo 9 Recombinante');


INSERT INTO postos_vacinacao (nome, endereco, tipo, contato) VALUES
('UBS Clementino Fraga', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('Multicentro Amaralina', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Alto das Pombas', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Menino Joel', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vila Matos', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Candeal Pequeno', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Manoel Vitorino', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Mãe Olga de Alaketu - Vale do Matatu', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Santa Luzia', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Zulmira Barros', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Imbui', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Curralinho', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Pituaçu', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Parque de Pituaçu', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Cesar de Araujo', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Dep Cristovao Ferreira - Saramandia', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Profº Drº Carlos Santana - Doron', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Fernando Filgueiras – Alto da Cachoeirinha - Cabula VI', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Arenoso', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('CSU Pernambues', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Nelson P. Dourado', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Cajazeiras V', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Jardim das Mangabeiras', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Palestina', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Jaguaripe', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Barbalho', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Ramiro de Azevedo', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Gamboa', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Prof. José Mariane', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Dr. Orlando Imbassahy', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Parque São Cristóvão', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vila Verde', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Ceasa', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Coração de Maria', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Prof. Eduardo Mamede', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Itapuã', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Virgílio de Carvalho', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Ministro Alkimin', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Joanes Leste', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Joanes Centro Oeste Hamesa', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF São José de Baixo', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('Multicentro Liberdade', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Santa Mônica', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF San Martin I', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vila Nova de Pituaçu', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vila Canária', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF São Marcos', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Edgar Pires da Veiga', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Canabrava', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Dom Avelar', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vale do Cambonas', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Sete de Abril', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('Saúde dos Bairros', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Lagoa da Paixão', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Deputado Luiz Braga', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Antonio Lazzarotto', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Capelinha', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Pirajá', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Alto do Cabrito', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Fazenda Coutos', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Itapuã II', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Suburbana', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Monte Azul', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Quingoma', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Cajazeiras', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Vila Mariana', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Rio Sena', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF São Cristóvão', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Sol Nascente', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Liberdade', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Tancredo Neves', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Arembepe', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Jardim São Paulo', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Largo do Tanque', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Baixa do Fiscal', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Coutos', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Periperi', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Bairro da Paz', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Candeal', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Santo Antônio', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Massaranduba', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Nordeste de Amaralina', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Pirajá', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Cabula', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Calabar', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF São Gonçalo do Retiro', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('USF Alto do Maron', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Retiro', 'Endereço desconhecido', 'Público', 'Contato desconhecido'),
('UBS Boa Vista', 'Endereço desconhecido', 'Público', 'Contato desconhecido');
