INSERT INTO vacina (nome_vac, data_aplicacao, local_aplicacao, tipo, dose, lote, obs, id_usuario) VALUES
('Vacina 1', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 2', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 3', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 4', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 5', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 6', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 7', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 8', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 9', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 10', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 11', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 12', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 13', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 14', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 15', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 16', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 17', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 18', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 19', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 20', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 21', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 22', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 23', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 24', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 25', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 26', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 27', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 28', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 29', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 30', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 31', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 32', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 33', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 34', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 35', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 36', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 37', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 38', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 39', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 40', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 41', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 42', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 43', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 44', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 45', '2007-02-15', 'USF Curralinho', 'Vacina Subunitária', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 46', '2007-02-15', 'USF Curralinho', 'Vacina de RNA Mensageiro (mRNA)', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 47', '2007-02-15', 'USF Curralinho', 'Vacina de Vetor Viral', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 48', '2007-02-15', 'USF Curralinho', 'Vacina de Proteína Recombinante', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 49', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Vivo Atenuado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2),
('Vacina 50', '2007-02-15', 'USF Curralinho', 'Vacina de Vírus Inativado', '1ª Dose', 'Lote não informado', 'Nenhuma observação', 2);
